language: r
cache: packages
sudo: false
warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

r_binary_packages:
  - Rcpp
  - RcppArmadillo
  - testthat

r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --as-cran"

